### ISSUE TITLE
Incorporate Flow library for type checking and improved code quality

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/structured-metadata-editor-react#11]
### Description
As the code becomes more complex, we should leverage the self-documenting and code quality tool, Flow.  https://flow.org/   

### Done Looks Like
- Flow is integrated into the project, and some functions are updated to use it's type checking.
- The pattern is started.  Doesn't have to be 100%, but it will help.

### Tasks
- [x] Install Flow
- [x] Implement on some target, first functions.

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by adamjarling** [comment]
So I've accomplished the scope of this ticket, however after digging into Flow and applying in bits and pieces to this application, I think we should wait on introducing it to the code base.  The type checking is awesome, and will be a great tool to use to keep this app strong and robust, however there is so much going on now with connecting Peak.js to the rest of the application, this will make a currently complicated code state even more complex.  Let's let the dust settle, then re-approach in a month or so, would be my recommendation.

@Dananji @cjcolvar @joncameron @davidschober @mcwhitaker

**Comment by Dananji** [comment]
@adamjarling Yes, I agree.

**Comment by adamjarling** [comment]
Ok, I have the branch saved locally.  We could close this ticket, as the initial work is done, then revisit the implementation when it makes more sense.
