### ISSUE TITLE
Alert for saving structure show up for inline form save button click

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/structured-metadata-editor-react#54]
### Description

If structure is edited after saving it to back-end server once, the alert for saving the structure shows up whenever save button is clicked on inline forms.

### Done Looks Like

The alert does not show when save buttons in inline forms are clicked

**Comment by Dananji** [comment]
@adamjarling I think the:point_up:issue happens because we don't clear the `alertObj` created in the respective component when the alert is closed from `AlertContainer`. I am 
 integrating alerts in the ticket I'm working (not allowing to add more segments once we have reached the end of the media file). For this I create an `alertObj` within `ButtonSection` component and clear it when we change between heading and timespan forms, and the alert completely goes away. But when I close the alert (with close button) and perform something else like deleting a timespan in the structure, the alert re-appears, which does not happen when it's cleared.

**Comment by Dananji** [comment]
@adamjarling Should I try and fix this as a part of the current work I'm doing?

**Comment by adamjarling** [comment]
Yes, if it makes sense to fix as part of your work, then I'd do it.  And when you submit your PR, just put an extra line: `fixes #54` to show it's part of the PR?

**Comment by Dananji** [comment]
Sure! Thanks :+1:
