### ISSUE TITLE
Bugs in editing timespans

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/structured-metadata-editor-react#55]
### Description

- If an existing timespan is selected for editing while adding a new timespan, an error is thrown.
- If an existing timespan is deleted while adding a new timespan, the Timespan form values show as `NaN:NaN:NaN`

related to #42

### Done Looks Like
- Only one list Item may be edited (or confirm deleted) at a time.
- All non-currently edited list items should have their controls set to disabled.

**Comment by Dananji** [comment]
@adamjarling  Do you think permitting only one action at a time is the solution for this? Like we did with inline timespan editing. Or something better?

**Comment by adamjarling** [comment]
Yes, to keep this simple, one "active" action at a time is best.   I'd say if a user is adding a new item, then maybe we disable all List Item controls, as long as a new form is open? 

And say a List Item is being edited, maybe we disable adding a new item?   Is this too complex to wire up?

**Comment by Dananji** [comment]
Yes, I agree.
No, I don't think it's going to be that complex. We can use a similar approach using redux-store like we did with inline editing.

**Comment by adamjarling** [comment]
@Dananji I'm going to have to hook into, or set up this service in #42.

**Comment by Dananji** [comment]
Yeah, sure!

**Comment by Dananji** [comment]
@adamjarling You did not set up this is in #42 right? If so, can I fix this?

**Comment by adamjarling** [comment]
@Dananji No I didn't fix this issue, I just used the same Redux `disable` pattern mentioned above.

**Comment by Dananji** [comment]
Ohh... yeah. :+1: I misunderstood that comment till now. My bad!
