### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/structured-metadata-editor-react#63]
### Description
Update and enhance the documentation for developers (and now users) of this application.

### Done Looks Like
- Documentation is clear and comprehensive

### To do
- [x] Investigate documentation tools which sync with Github?
- [x] Update documentation to reflect current state of application, tips and tricks for local development (ie. how to run local data, etc).

**Comment by Dananji** [comment]
@adamjarling  We don't have a large amount of documentation for the application at the moment. So, I suggest we use either a comprehensive README or GitHub wiki for this.
I think using Wiki is the better option, because we have the space to grow. What do you think?

**Comment by cjcolvar** [comment]
We talked about user-facing documentation during sprint planning and if it should live in github (to be useful for other apps which might use this tool) or in Avalon's collection manager's guide.

I think it might be best to have it both places but maybe that is too much overhead at the moment to synchronize the two?

**Comment by adamjarling** [comment]
@cjcolvar @Dananji Let's try both places?   And just treat documentation and it's updated status a priority. 

I like the idea of a comprehensive, need to know info, overview in the README.   Then use the Wiki section to get as detailed as we like?   For both developers, and consumers of the application.

**Comment by Dananji** [comment]
@adamjarling Sounds good :+1: I will create the GitHub Wiki and ping you. If everything is in order, then we can update the collection manager's guide?

**Comment by Dananji** [comment]
@adamjarling This is the link to the Wiki, https://github.com/avalonmediasystem/structured-metadata-editor-react/wiki
If anything needs to be changed, please let me know.
