### ISSUE TITLE
When editing timespans, user cannot see both Waveform and inline edit form at the same time

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/structured-metadata-editor-react#65]
### Description

When editing a timespan with the use of segment handles in the waveform, the user cannot see the respective inline form when the timespan is at the bottom of the tree (even in the middle depending on the screen size of the device the user is using).

**Comment by Dananji** [comment]
@joncameron Could you please add your thoughts on this? What would a real user expect in this scenario?

**Comment by mcwhitaker** [comment]
@Dananji How hard would it be to add a vertical scroll bar to the inline form? If not to hard, that would be my suggestion for @joncameron  and @davidschober .

**Comment by Dananji** [comment]
@mcwhitaker Do you mean a vertical scroll bar for the section of the application (structure tree) containing the inline form? So that, we can scroll the section with inline form separately? Yeah, I think we can do that. It would be a task with a medium-level effort, I guess.

**Comment by mcwhitaker** [comment]
Yes, that is what I mean. The POs will need to decide. From the Usability perspective, that will seem important to do, but I know we are trying to contain the scope of the SME.
